name: nepali_food_recipes
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-Bold.ttf
        - asset: fonts/Dosis-Regular.ttf
        - asset: fonts/Dosis-SemiBold.ttf


