name: nepali_food_recipes
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.4
  timelines: ^0.1.0
  firebase_core: ^1.10.5
  cloud_firestore: ^3.1.4
  firebase_auth: ^3.3.3
  provider: ^6.0.1
  google_sign_in: ^5.2.1
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.3
  liquid_swipe: ^2.1.1
  lottie: ^1.2.1
  shared_preferences: ^2.0.11
  flutter_local_notifications: ^9.1.5
  firebase_analytics: ^9.0.3
  share: ^2.0.4
  firebase_messaging: ^11.2.3




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-Bold.ttf
        - asset: fonts/Dosis-Regular.ttf
        - asset: fonts/Dosis-SemiBold.ttf



