name: nepali_food_recipes
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.4
  timelines: ^0.1.0
  firebase_core: ^1.10.4
  cloud_firestore: ^3.1.3
  firebase_auth: ^3.3.2
  provider: ^6.0.1
  google_sign_in: ^5.2.1
  cached_network_image: ^3.2.0
  image_picker: ^0.8.3
  firebase_storage: ^10.2.2
  liquid_swipe: ^2.1.1
  lottie: ^1.2.1
  shared_preferences: ^2.0.9
  flutter_local_notifications: ^9.1.4
  firebase_analytics: ^9.0.1
  share: ^2.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-Bold.ttf
        - asset: fonts/Dosis-Regular.ttf
        - asset: fonts/Dosis-SemiBold.ttf



